name: drl
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - anyio=4.11.0=pyhcf101f3_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py310h29418f3_0
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.14.2=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - brotli-python=1.1.0=py310h73ae2b4_4
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.8.3=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cffi=2.0.0=py310h29418f3_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.10.18=py310hd8ed1ab_0
  - debugpy=1.8.17=py310h699e580_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=hac47afa_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh3521513_0
  - ipython=8.37.0=pyha7b4d00_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py310h5588dad_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh5737063_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.9=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - krb5=1.21.3=hdf4eb48_0
  - lark=1.3.0=pyhd8ed1ab_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.20=hc70643c_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.1.4=pyhcf101f3_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook=7.4.7=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - openssl=3.5.4=h725018a_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - platformdirs=4.4.0=pyhcf101f3_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.10.18=h981015d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py310h282bd7d_1
  - pywinpty=2.0.15=py310h9e98ed7_0
  - pyzmq=27.1.0=py310h535538e_0
  - referencing=0.36.2=pyh29332c3_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.27.1=py310h034784e_1
  - send2trash=1.8.3=pyh5737063_1
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - terminado=0.18.1=pyh5737063_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.14=h5e9d12e_1
  - tomli=2.2.1=pyhe01879c_2
  - tornado=6.5.2=py310h29418f3_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20250822=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - ucrt=10.0.26100.0=h57928b3_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h818238b_31
  - vcomp14=14.44.35208=h818238b_31
  - vs2015_runtime=14.44.35208=h38c0c73_31
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=py310haa95532_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=h6a83c73_3
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h8cc25b3_1
  - zstandard=0.23.0=py310h29418f3_3
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - async-timeout==5.0.1
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - cloudpickle==3.1.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - deap==1.4.3
      - et-xmlfile==2.0.0
      - farama-notifications==0.0.4
      - filelock==3.13.1
      - fonttools==4.58.2
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==1.2.2
      - jinja2==3.1.4
      - joblib==1.5.2
      - kiwisolver==1.4.8
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - multidict==6.6.3
      - networkx==3.3
      - numpy==2.2.6
      - openpyxl==3.1.5
      - pandas==2.3.0
      - patsy==1.0.2
      - pillow==11.0.0
      - pip==25.3
      - propcache==0.3.2
      - psutil==7.0.0
      - pyparsing==3.2.3
      - pyyaml==6.0.2
      - requests==2.32.4
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - setuptools==80.9.0
      - statsmodels==0.14.5
      - sumtree==0.2.7
      - sympy==1.13.3
      - threadpoolctl==3.6.0
      - torch==2.7.1+cu118
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt27cu118
      - torchaudio==2.7.1+cu118
      - torchvision==0.22.1+cu118
      - tqdm==4.67.1
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - yarl==1.20.1
prefix: D:\anaconda3\envs\drl
